import "./globals.css";
import Navbar from "./../components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { Button } from "@/components/ui/button";
import Link from "next/link";
export const metadata = {
  title: "Blinds, Shades, Shutters & Drapery Installation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Navbar />

        {children}

        <Footer />
        <div className="md:hidden flex flex-row sticky position-fixed w-[100%] bottom-0 ">
          <div className="w-[50%]">
            <Button variant="ghost" className="w-full">
              Call Us
            </Button>
          </div>
          <div className="w-[50%]">
            <Link href="/services/consultation">
              <Button variant="destructive" className="w-full">
                Request A Consultant
              </Button>
            </Link>
          </div>
        </div>
      </body>
    </html>
  );
}
